### ISSUE TITLE
ccda-validator results difference

### ISSUE THREAD

**Issue by panther008** [siteadmin/reference-ccda-validator#19]
Hi,
I have implemented your ccda validator but the validator results are different than the  validator results in [TTPEDGE SITE](https://ttpedge.sitenv.org/ttp/#/direct/validator/ccda/r2 ). Please let me know how can I get exact same results as ttedge site using your validator.
![issue2](https://user-images.githubusercontent.com/10078427/31178102-7cac9e6a-a931-11e7-8a40-8282bb04dd1b.png)
This is the result generated by ttpedge site while below is the result generated by your validator 

![validator](https://user-images.githubusercontent.com/10078427/31178271-f6301a64-a931-11e7-8338-29d9bef8c87c.png)
these results are generated for negative test ccds
Thanks in advance!

**Comment by pr-github** [comment]
Hi panther008,
Make sure that you have loaded the complete set of code systems and valuesets as mentioned in the repo. Getting only Vocabulary Infos' and no errors or warnings, indicates that the codes might be missing. However sharing a few of your generated "ONC 2015 S&CC Vocabulary Validation Conformance Info" would give an exact idea about the issue you are facing.
Thanks!

**Comment by panther008** [comment]
Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.16926) that do not exist in service for code system CONFIDENTIALITY (2.16.840.1.113883.5.25)
/ClinicalDocument[1]/confidentialityCode[1]
Line Number:32

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.11526) that do not exist in service for code system null (null)
/ClinicalDocument[1]/languageCode[1]
Line Number:33

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.80.63) that do not exist in service for code system null (null)
/ClinicalDocument[1]/languageCode[1]
Line Number:33

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.1) that do not exist in service for code system ADMINISTRATIVEGENDER (2.16.840.1.113883.5.1)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/administrativeGenderCode[1]
Line Number:60

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12212) that do not exist in service for code system MARITALSTATUSCODE (2.16.840.1.113883.5.2)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/maritalStatusCode[1]
Line Number:63

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.19185) that do not exist in service for code system HL7 RELIGIOUS AFFILIATION (2.16.840.1.113883.5.1076)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/religiousAffiliationCode[1]
Line Number:64

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.2074.1.1.3) that do not exist in service for code system RACE & ETHNICITY - CDC (2.16.840.1.113883.6.238)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/raceCode[1]
Line Number:67

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.14914) that do not exist in service for code system RACE & ETHNICITY - CDC (2.16.840.1.113883.6.238)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/sdtc:raceCode[1]
Line Number:69

Info:Value set code validation attempt for value set(s) ('2.16.840.1.114222.4.11.837) that do not exist in service for code system RACE & ETHNICITY - CDC (2.16.840.1.113883.6.238)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/ethnicGroupCode[1]
Line Number:70

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.11526) that do not exist in service for code system null (null)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/languageCommunication[1]/languageCode[1]
Line Number:72

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12249) that do not exist in service for code system LANGUAGEABILITYMODE (2.16.840.1.113883.5.60)
/ClinicalDocument[1]/recordTarget[1]/patientRole[1]/patient[1]/languageCommunication[1]/modeCode[1]
Line Number:74

Info:Value set code validation attempt for value set(s) ('2.16.840.1.114222.4.11.1066) that do not exist in service for code system null (null)
/ClinicalDocument[1]/author[1]/assignedAuthor[1]/code[1]
Line Number:98

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.80.32) that do not exist in service for code system CPT-4 (2.16.840.1.113883.6.12)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[5]/section[1]/entry[1]/encounter[1]/code[1]
Line Number:1132

Info:Value set code validation attempt for value set(s) ('2.16.840.1.114222.4.11.1066) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[5]/section[1]/entry[1]/encounter[1]/performer[1]/assignedEntity[1]/code[1]
Line Number:1147

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[1]/substanceAdministration[1]/statusCode[1]
Line Number:1470

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[2]/substanceAdministration[1]/statusCode[1]
Line Number:1510

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NATIONAL CANCER INSTITUTE (NCI) THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[1]/substanceAdministration[1]/routeCode[1]
Line Number:1472

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NATIONAL CANCER INSTITUTE (NCI) THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[2]/substanceAdministration[1]/routeCode[1]
Line Number:1512

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.6) that do not exist in service for code system CVX (2.16.840.1.113883.12.292)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[1]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:1479

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.6) that do not exist in service for code system CVX (2.16.840.1.113883.12.292)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[2]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:1521

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.19717) that do not exist in service for code system HL7 ACTNOIMMUNIZATIONREASON (2.16.840.1.113883.5.8)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[8]/section[1]/entry[2]/substanceAdministration[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:1542

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED,2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[16]/section[1]/entry[3]/encounter[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:2247

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[1]/substanceAdministration[1]/statusCode[1]
Line Number:656

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[2]/substanceAdministration[1]/statusCode[1]
Line Number:685

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[3]/substanceAdministration[1]/statusCode[1]
Line Number:719

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[4]/substanceAdministration[1]/statusCode[1]
Line Number:751

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[5]/substanceAdministration[1]/statusCode[1]
Line Number:780

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.159331) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[6]/substanceAdministration[1]/statusCode[1]
Line Number:810

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NCI THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[1]/substanceAdministration[1]/routeCode[1]
Line Number:664

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NCI THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[2]/substanceAdministration[1]/routeCode[1]
Line Number:696

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NCI THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[3]/substanceAdministration[1]/routeCode[1]
Line Number:727

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NCI THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[4]/substanceAdministration[1]/routeCode[1]
Line Number:760

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NCI THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[5]/substanceAdministration[1]/routeCode[1]
Line Number:789

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.7) that do not exist in service for code system NCI THESAURUS (2.16.840.1.113883.3.26.1.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[6]/substanceAdministration[1]/routeCode[1]
Line Number:820

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.4) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[1]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:673

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.4) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[2]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:705

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.4) that do not exist in service for code system (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[3]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:739

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.4) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[4]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:768

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.4) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[5]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:798

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.4) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[2]/section[1]/entry[6]/substanceAdministration[1]/consumable[1]/manufacturedProduct[1]/manufacturedMaterial[1]/code[1]
Line Number:829

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.52) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[16]/section[1]/entry[3]/encounter[1]/code[1]
Line Number:2235

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:930

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[2]/act[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:972

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[3]/act[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:1015

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[4]/act[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:1070

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[5]/section[1]/entry[1]/encounter[1]/entryRelationship[1]/act[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:1190

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_SNOMED) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[6]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/code[1]
Line Number:1258

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/code[1]/translation[1]
Line Number:934

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[2]/act[1]/entryRelationship[1]/observation[1]/code[1]/translation[1]
Line Number:976

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[3]/act[1]/entryRelationship[1]/observation[1]/code[1]/translation[1]
Line Number:1019

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[4]/act[1]/entryRelationship[1]/observation[1]/code[1]/translation[1]
Line Number:1071

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[5]/section[1]/entry[1]/encounter[1]/entryRelationship[1]/act[1]/entryRelationship[1]/observation[1]/code[1]/translation[1]
Line Number:1192

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.2_LOINC) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[6]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/code[1]/translation[1]
Line Number:1262

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:944

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[2]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:986

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[3]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:1029

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system SNOMED-CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[4]/section[1]/entry[4]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:1085

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system (2.16.840.1.113883.6.90)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[5]/section[1]/entry[1]/encounter[1]/entryRelationship[1]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:1199

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system ICD-10 (2.16.840.1.113883.6.90)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[6]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:1272

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[1]/procedure[1]/code[1]
Line Number:1318

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[2]/procedure[1]/code[1]
Line Number:1360

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.9) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[1]/procedure[1]/targetSiteCode[1]
Line Number:1323

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.8.9) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[7]/section[1]/entry[2]/procedure[1]/targetSiteCode[1]
Line Number:1365

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.7.4) that do not exist in service for code system (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[1]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/entryRelationship[2]/observation[1]/value[1]
Line Number:529

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/component[1]/observation[1]/code[1]
Line Number:1799

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/component[2]/observation[1]/code[1]
Line Number:1820

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[1]/observation[1]/code[1]
Line Number:1859

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[2]/observation[1]/code[1]
Line Number:1885

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[3]/observation[1]/code[1]
Line Number:1906

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[4]/observation[1]/code[1]
Line Number:1930

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[5]/observation[1]/code[1]
Line Number:1954

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/component[1]/observation[1]/statusCode[1]
Line Number:1803

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/component[2]/observation[1]/statusCode[1]
Line Number:1824

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[1]/observation[1]/statusCode[1]
Line Number:1863

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[2]/observation[1]/statusCode[1]
Line Number:1889

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[3]/observation[1]/statusCode[1]
Line Number:1910

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[4]/observation[1]/statusCode[1]
Line Number:1934

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.39) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[5]/observation[1]/statusCode[1]
Line Number:1958

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12839) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/component[1]/observation[1]/value[1]
Line Number:1805

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12839) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/component[2]/observation[1]/value[1]
Line Number:1826

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12839) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[4]/observation[1]/value[1]
Line Number:1936

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12839) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/component[5]/observation[1]/value[1]
Line Number:1960

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[1]/organizer[1]/code[1]
Line Number:1787

Info:Value set code validation attempt for value set(s) ('null) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[11]/section[1]/entry[2]/organizer[1]/code[1]
Line Number:1847

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.6.8) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[1]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:513

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.6.2) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[1]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:479

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.3221.6.2) that do not exist in service for code system SNOMED CT (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[1]/section[1]/entry[2]/act[1]/entryRelationship[1]/observation[1]/value[1]
Line Number:571

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.1) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[1]/section[1]/entry[1]/act[1]/entryRelationship[1]/observation[1]/participant[1]/participantRole[1]/playingEntity[1]/code[1]
Line Number:490

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113762.1.4.1010.1) that do not exist in service for code system RXNORM (2.16.840.1.113883.6.88)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[1]/section[1]/entry[2]/act[1]/entryRelationship[1]/observation[1]/participant[1]/participantRole[1]/playingEntity[1]/code[1]
Line Number:582

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.11.20.9.41) that do not exist in service for code system (2.16.840.1.113883.6.96)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[10]/section[1]/entry[1]/observation[1]/value[1]
Line Number:1677

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.80.62) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[9]/section[1]/entry[1]/organizer[1]/component[1]/observation[1]/code[1]
Line Number:1602

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.3.88.12.80.62) that do not exist in service for code system LOINC (2.16.840.1.113883.6.1)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[9]/section[1]/entry[1]/organizer[1]/component[2]/observation[1]/code[1]
Line Number:1615

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12839) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[9]/section[1]/entry[1]/organizer[1]/component[1]/observation[1]/value[1]
Line Number:1605

Info:Value set code validation attempt for value set(s) ('2.16.840.1.113883.1.11.12839) that do not exist in service for code system null (null)
/ClinicalDocument[1]/component[1]/structuredBody[1]/component[9]/section[1]/entry[1]/organizer[1]/component[2]/observation[1]/value[1]
Line Number:1618

**Comment by pr-github** [comment]
Hi panther008,
Seems that I guessed it right. You do not have required valueset and code system files as mentioned in the repo. You may have a look at [Code Validator API Docs](https://github.com/siteadmin/code-validator-api/tree/master/codevalidator-api/docs) for further help. In case you have already downloaded them,

>1. Create a directory that will hold the vocabulary artifacts. For example, /path/to/validator_configuration
        a. this folder will contain the needed vocabulary configuration files

>2. Place the ccdaReferenceValidatorConfig.xml in this folder. For example, /path/to/validator_configuration/ccdaReferenceValidatorConfig.xml
      a. this file contains the xpath expressions that target particular nodes in the given C-CDA to be validated. Each expression is configured with at least one validator.

> 3.Create a local directory for Codes, Valuesets and Scenario files. For example,
     a. /path/to/validator_configuration/vocabulary/code_repository
     b. /path/to/validator_configuration/vocabulary/valueset_repository/VSAC
     c. /path/to/validator_configuration/scenarios

Thanks!

**Comment by panther008** [comment]
Thank you so much for your help. I'll implement it as you said and let you know if issue is solved.

**Comment by panther008** [comment]
Hi,
Can you please provide me a link to required value sets?so that I can download it.

Thanks!

**Comment by pr-github** [comment]
Hi panther008,
All the required details about each valueset, along with links to obtain those are already mentioned in [Code Validator API Docs](https://github.com/siteadmin/code-validator-api/tree/master/codevalidator-api/docs). Please go through it carefully.
Thanks!
