### ISSUE TITLE
Where do I acquire the scenarios referenced in README.md? Any tutorials I should be reviewing?

### ISSUE THREAD

**Issue by jonbartels** [siteadmin/reference-ccda-validator#20]
I am reviewing [README.md](https://github.com/siteadmin/reference-ccda-validator/blob/master/README.md) . It says:

> Scenario files needed for content validation

Where do I get these scenario files? I expect these to be the PDFs *and* the schemas and schematrons which are listed at [The main ETT/TTT testing site](https://ttpedge.sitenv.org/ttp/#/validators) . I found the PDFs [at this project](https://github.com/siteadmin/2015-Certification-C-CDA-Test-Data). Am I looking in the right place? Are my expectations correct or should I be looking for different data?

I figured out where to get the vocabulary (I think!) from [the readme at the codevalidator project](https://github.com/siteadmin/code-validator-api/blob/master/codevalidator-api/docs/ReadMe.txt)

My objective is to get a local copy of the validator running so I can properly and automatically unit test output from my software against the validator. Are there any other guides or tutorials I should be reviewing beyond the project READMEs to meet this objective?

Are there guides or rules I should be aware of when running a local copy of the validator to ensure my local copy provides output which matches the official standards?

**Comment by etiology** [comment]
+1

**Comment by jonbartels** [comment]
I found [this thread](https://groups.google.com/forum/#!topic/edge-test-tool/N0pZQ_Bgtw8) on the ETT mailing list. It outlines some of the config steps. 

More importantly it points to the [binary releases](https://github.com/siteadmin/reference-ccda-validator/releases) for reference-ccda-validator 

@etiology - I appreciate the +1. Can you comment with anything you've found so far?

**Comment by Plow74** [comment]
The scenario files are gold-standard CCDAs that have specific content (names, addresses, etc.) which are used for the content validation portion of CCDA validation. I believe they are not distributed due to licensing. I forwarded this question to the author of the content validator library so we can provide a better answer and update our documentation with a better explanation.

**Comment by etiology** [comment]
@jonbartels - I should have added more details.  We were also really unclear where this 'scenarios' resource was supposed to come from.  

Currently I see this in my tomcat instance since this seems related:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'scenarios' is defined
```
any thoughts on this?  this is using the 1.0.23 release

**Comment by Plow74** [comment]
To get past the error, create an empty scenario directory and point the configuration to that directory. Scenario files are specifically for certification and are not required for validation. Also, there is no place to download them.
We have a ticket in the backlog to address concerns with the current documentation, so your input is very much appreciated.

**Comment by etiology** [comment]
@Plow74 When you say ```The scenario files are gold-standard CCDAs that have specific content (names, addresses, etc.) which are used for the content validation portion of CCDA validation.```, are you referring to the "Gold_Samples_For_Practice" directory found on [ttpedge.siteenv.org](https://ttpedge.sitenv.org/ttp/#/validators)?

It contains the following files:
```
170.315_b1_toc_gold_sample1_v3.xml
170.315_b1_toc_gold_sample1_v5.pdf
170.315_b1_toc_gold_sample2_v3.pdf
170.315_b1_toc_gold_sample2_v3.xml
```

Can you clarify if these files should be moved into the folder described in the **referenceccdaservice.xml**?

**Comment by Plow74** [comment]
All of the scenario ccdas (the gold standard ones) are xml. The files you have listed are examples for vendors to use, but not the gold standard CCDAs themselves. 
Scenario files are not needed for validating a CCDA - they are only needed for vendors working towards certification. 
The scenario files have very specific, pre-canned data in them that is used to determine if a system is producing CCDAs correctly. The reference validator determines that a vendor's CCDA has the expected content by comparing the uploaded CCDA against the a gold standard CCDA.

Hope this helps. Again, for validating CCDAs, the scenario files are NOT needed. Right now the validator expects the directory to be on the file system, but it should be empty for most use cases. Perhaps we will make this easier to configure in a future release.

**Comment by etiology** [comment]
@Plow74 What about the missing 'bean' for Scenario files?  Do you have any insite on that?  Java is not my primary language so I'm unclear what this means.

**Comment by Plow74** [comment]
To get rid of that error, create the scenarios directory - keeping it empty - and point the configuration to that empty directory.

**Comment by jonbartels** [comment]
@etiology - I think you're further ahead than I am. Other than the scenarios are you getting the same outpu
