### ISSUE TITLE
Artifactory down / not reachable

### ISSUE THREAD

**Issue by stkleinbaum** [siteadmin/reference-ccda-validator#23]
Hi,

I can not build the validator locally because Artifactory (http://devsoap.sitenv.org:8081/artifactory/libs-release and http://devsoap.sitenv.org:8081/artifactory/plugins-release-local) is down / not reachable. When will Artifactory be up again? Are the artifacts also published to maven central?

Best

**Comment by drbgfc** [comment]
Hi,
We do have an SSL issue we would like to address if accessing the artifactory site directly via a browser, However, accessing the dependencies via maven should work fine. I recently ran a ref val build without issue. Is this still an issue for you? Unfortunatley the artifacts are not in maven central.
Thanks,
Dan

**Comment by drbgfc** [comment]
Closing as no response / no issue on our end
