### ISSUE TITLE
Setting up project (missing codesystem,valueset files)

### ISSUE THREAD

**Issue by usmanq8** [siteadmin/reference-ccda-validator#26]
How can i get codesystem and valueset files for this project.
I read a closed issue reporting that you cannot provide due to licensing issues.
how about using valuesets from.

http://art-decor.org/decor/services/ValueSetIndex

**Comment by drbgfc** [comment]
Collect as many as you can from VSAC first. For the ones you can't get from VSAC or aren't provided in the repo/instructions, you have to hand-create them to fit the VSAC format.
