### ISSUE TITLE
Valueset files not loaded

### ISSUE THREAD

**Issue by usmanq8** [siteadmin/reference-ccda-validator#27]
I placed the value set file that your project Code validator had.
Do i also need to have Code System file to run the project or just Valueset is fine as well.
I have enabled Debug logs but it says Valuesets loaded but when i use 

http://localhost:8080/referenceccdaservice/swagger-ui.html#!/reference-ccda-validation-controller/getValuesetsByOidsUsingGET

to find the valueset it returns empty message.

**Comment by drbgfc** [comment]
You will need the code systems for there to be any use to the value sets. You will need to get these from their authoritive sources as those are the ones we have programmed the application to handle. The application will work with any number of them there, or not, but the ones which are not there will not be enforced. 

https://github.com/siteadmin/code-validator-api/tree/master/codevalidator-api/docs
https://github.com/siteadmin/code-validator-api/blob/master/codevalidator-api/docs/Code%20Systems.xlsx
