### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by jxfish2** [siteadmin/reference-ccda-validator#28]
I see that you include a scripts directory, with lots and lots of Windows batch files.

Maybe I need to ask a stupid question:

Will this application run in a Linux environment?

I ask, because I do not see any Linux / Unix scripts.

**Comment by drbgfc** [comment]
Those appear to be maven scripts. I'm personally not sure why they were pushed to the repo. But, to answer you question, you can definitely run the reference-ccda-validator in Linux. The prod instance for SITE/ETT is running on a Linux box right now.
