### ISSUE TITLE
Reference CCDA Validator Difference Issue

### ISSUE THREAD

**Issue by BlackHawkRey** [siteadmin/reference-ccda-validator#37]
We have deployed the CCDA Validator according to the instructions and the validation process seems to work except we are getting differences between the the results from our on-premise Validator and the one hosted by the https://ttpedge.sitenv.org/ttp/#/validators/ccdar2 site.

Mine:
![image](https://user-images.githubusercontent.com/43356506/45687890-eed23780-bb1d-11e8-84fb-b5542b3eb234.png)

Online Validator:
![image](https://user-images.githubusercontent.com/43356506/45687923-fdb8ea00-bb1d-11e8-8fb9-ae9488ff2772.png)

One example of the differences is when validating file: 170.315_b9_cp_amb_sample1_v5.xml
The differences seem to be related to the scenario files where our validation does not find errors but the online one does, specifically with the basic patient info as shown below:

Error - Patient First Name Expected = Karen but, submitted file contains first name of Eve
Line number: 0
Error - Patient Last Name Expected = Mckiney but, submitted file contains last name of Betterhalf
Line number: 0
Error - The scenario requires patient middle name, but submitted file does not have patient middle name
Line number: 0
Warning - The scenario requires patient previous name, but submitted file does not have patient previous name
Line number: 0
Error - Patient Date of Birth Expected = 19700501 but, submitted file contains Date of Birth of 19750501
Line number: 0
Error - Patient Granular Race Code = 2108-9 expected in sdtc:raceCode extension but, submitted file does not contain the expected granular race code
Line number: 0
Warning - Patient Telecom in the submitted file does not match the expected Telecom. The following values are expected: telecom/@use = HP and telecom/@value = tel:+1(555)777-1234
Line number: 0

We downloaded the scenario files from here and they have the Eve Betterhalf patient in it
https://ttpedge.sitenv.org/ttp/#/validators/documents 

Also, I am not sure if I have all the files I need in the Value Set. I downloaded them from here: https://vsac.nlm.nih.gov/valueset/expansions?pr=ccda&rel=C-CDA%20R2.1%202018-06-15 
There are 111 files.
In addition I also downloaded the ValueSetsHandCreatedbySITE hosted here: https://github.com/siteadmin/code-validator-api/tree/master/codevalidator-api/docs/ValueSetsHandCreatedbySITE

I currently do not have anything in the Code_Repository folder as the CodeSystems file references multiple code types and there are thousands in the VSAC site and I am not sure if we need them all or just a few.

I saw the Issue posted by another user with a similar situation as mine but the solutions provided didn't seem to help me.

I am attaching a copy of my Validator setup, I had to remove some of the files in the VSAC folder and all of the scenario files in order to be able to upload it here due to file size requirements. I mainly would like to know if the configuration looks good.

Please let me know,

Thanks.

[reference-ccda-validator.zip](https://github.com/siteadmin/reference-ccda-validator/files/2392655/reference-ccda-validator.zip)

**Comment by drbgfc** [comment]
The specific codesystems used in SITE listed here: https://github.com/siteadmin/code-validator-api/blob/master/codevalidator-api/docs/Code%20Systems.xlsx 
They must be obatined from their original sources due to licensing issues and placed in your folder to match SITE. Some of them may require a purchase to download.

I will look at the setup when I have time. Thanks, Dan.

**Comment by BlackHawkRey** [comment]
Hi Dan, thanks for taking a look at the setup, we really need the help.
We suspect the main issue we are having is related with the scenarios. Like I mentioned before, I downloaded the scenario files I have on my setup from the TTPEdge site - Documents section: https://ttpedge.sitenv.org/ttp/#/validators/documents so we don't know which one is the right one, the one currently hosted on the TTPEdge Validator with the Karen McKiney patient or the one in the TTPEdge site documents section with the Eve Betterhalf patient. I am sure that is not the only difference but is just an example I have for you.
Please let us know ASAP, we need to fix the Validator to be able to finalize our certification testing.
Thanks.

**Comment by drbgfc** [comment]
The scenario files and all related C-CDA test files should be optained from this repo:
https://github.com/siteadmin/2015-certification-ccda-testdata

Please direct future support questions to this thread if possible instead of in the github issues:
https://groups.google.com/forum/#!forum/edge-test-tool

Feel free to copy and paste out entire question and add new questions when starting the thread.

Thanks for doing such a great job with your writeup/all the details. I should have more time later this week to look into it more.

**Comment by BlackHawkRey** [comment]
Ok, thanks. I will move it to the Google Groups and I just checked and that repository has the same Eve Betterhalf patient as the one from the TTPEdge site documents section which is what we are using.

**Comment by jwaga** [comment]
Hey. Excuse me for writing in the closed issue, but the context is good - I also have trouble with validation messages like 
```"The scenario requires patient previous name, but submitted file does not have patient previous name"```
I can see from google search that the https://groups.google.com/d/forum/edge-test-tool contains some information on these and other errors I'm observing.
It seems that the group is closed or non-existent. Is there a way I can access this content? Has it moved somewhere?
I've set up an account on https://ttpedge.sitenv.org/ttp/#/validators, also wrote an emal to edge-testing-tool@googlegroups.com but to no avail (the email returned `address not found`).
Anyone has some information on this?
Thanks.

**Comment by drbgfc** [comment]
Hi,
It exists but is private.

Try sending an email to:
edge-test-tool+subscribe@googlegroups.com

Here is the about page:
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!aboutgroup/edge-test-tool

If that doesn't work try asking here on the contact page:
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!aboutgroup/edge-test-tool
