### ISSUE TITLE
Error in README instructions

### ISSUE THREAD

**Issue by enieto-carecloud** [siteadmin/reference-ccda-validator#41]
In the instructions, the following Note is present:
> For the valueset_repository, assuming the path above of /path/to/validator_configuration/vocabulary/valueset_repository/VSAC/, please ensure that the valueset repository spreadsheet files are in the aformentioned subfolder labeled VSAC. However, please **do NOT include this VSAC folder in the referenceccdaservice.xml config file**

However, the sample Server Configuration has the following line:
`<Parameter name="vocabulary.localValueSetRepositoryDir" value="/path/to/validator_configuration/vocabulary/valueset_repository/VSAC" override="true"/>`

..and I think the previous it should be changed to:
`<Parameter name="vocabulary.localValueSetRepositoryDir" value="/path/to/validator_configuration/vocabulary/valueset_repository" override="true"/>`

**Comment by drbgfc** [comment]
Hi,

Good catch, although the actual sample config file here is correct as per the readme:
https://github.com/siteadmin/reference-ccda-validator/blob/master/configuration/referenceccdaservice.xml
...The readme itself displays an incorrect snippet under the 'Server Configuration' heading.

I will update this and once done provide the commit here and close this issue.

Thanks,
Dan

**Comment by drbgfc** [comment]
I have updated this in the develop branch. It will be merged later.

https://github.com/siteadmin/reference-ccda-validator/commit/7d778ea3fdb95cf0c7b528454186d3191853a562

It includes an update for using dynamic vocab as well.

Thanks.

Let me know if you see any issues.

**Comment by enieto-carecloud** [comment]
Thank you!
