### ISSUE TITLE
Failed to collect dependencies at org.eclipse.mdht:org.eclipse.mdht.uml.hl7.vocab:jar:3.0.0.201805310501

### ISSUE THREAD

**Issue by usmanq8** [siteadmin/reference-ccda-validator#42]
I am suddenly unable to compile project due to below issue: is the site properly working?
I am using Version: 1.0.33

`Could not resolve dependencies for project org.sitenv:referenceccdavalidator:jar:1.0.33: Failed to collect dependencies at org.eclipse.mdht:org.eclipse.mdht.uml.hl7.vocab:jar:3.0.0.201805310501: Failed to read artifact descriptor for org.eclipse.mdht:org.eclipse.mdht.uml.hl7.vocab:jar:3.0.0.201805310501: Could not transfer artifact org.eclipse.mdht:org.eclipse.mdht.uml.hl7.vocab:pom:3.0.0.201805310501 from/to java-net-public (https://maven.java.net/content/groups/public/): maven.java.net: Unknown host maven.java.net -> [Help 1]`

**Comment by drbgfc** [comment]
Apologies. We lost access to our repository server and are in the process of spinning up a new one. The new one should be available by EOM at the latest.

**Comment by drbgfc** [comment]
If you need the jars in the meantime they can be obtained here:
https://github.com/mdht/mdht-models/releases

**Comment by usmanq8** [comment]
any update if that is fixed ?

**Comment by drbgfc** [comment]
Unfortunately no. I had really hoped it would be but we don't have a server we can use yet. For the latest pom I updated to use my local file path, you will need to adjust accordingly to build yourself until the new server is obtained/setup.

**Comment by drbgfc** [comment]
Update: This is fixed. I have spent a good deal of time setting up a new server/migrating the old servers/creating new builds/etc. You will find that the latest pom points to this data:  https://github.com/siteadmin/reference-ccda-validator/commit/5cadc2fb51321739a73b42030b48a6f21cc91f9b

However, this is still in dev. This should be merged to master and part of the 1.0.38 ref val release on 2018 12 31 (EOM).

Thanks,
Dan
