### ISSUE TITLE
Errors during startup.

### ISSUE THREAD

**Issue by jxfish2** [siteadmin/reference-ccda-validator#55]
Getting the following errors when I attempt to start the service:

ERRORS IN referenceccdaservice.2019-03-18.log:

11:59:37,707 WARN  [AnnotationConfigWebApplicationContext:546] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'referenceContentValidator' defined in file [/opt/tomcat/temp/0-referenceccdaservice/WEB-INF/classes/org/sitenv/referenceccda/validators/content/ReferenceContentValidator.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.service.ContentValidatorService]: : Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
11:59:37,725 ERROR [ContextLoader:353] Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'referenceContentValidator' defined in file [/opt/tomcat/temp/0-referenceccdaservice/WEB-INF/classes/org/sitenv/referenceccda/validators/content/ReferenceContentValidator.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.service.ContentValidatorService]: : Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException

ERRORS IN localhost.log:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'referenceContentValidator' defined in file [/opt/tomcat/temp/0-referenceccdaservice/WEB-INF/classes/org/sitenv/referenceccda/validators/content/ReferenceContentValidator.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.service.ContentValidatorService]: : Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentValidatorService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'refModelHashMap' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.sitenv.contentvalidator.configuration.ScenarioLoader]: : Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scenarioLoader' defined in org.sitenv.contentvalidator.configuration.ContentValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException

ERRORS IN catalina.out:

SEVERE: Context [/referenceccdaservice] startup failed due to previous errors

**Comment by jxfish2** [comment]
**"LOADING SCENARIO FILES AT /opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/scenarios/"**

Why is this trying to load scenario files from 7.0.53, when we are running 7.0.93 ?

Why are we trying to load from the "mdht" subdirectory, when this subdirectory does not exist?

If this subdirectory is supposed to exist, what might I have missed?

**Comment by drbgfc** [comment]
It sounds like your referenceccdaservice.xml is not setup for your local computer's file structure. Those settings are our default settings for our production server. Can you share your referenceccdaservice.xml file? It should be located in your tomcat installation/conf/Catalina/localhost

**Comment by jxfish2** [comment]
<Context reloadable="true">
    <Parameter name="vocabulary.localCodeRepositoryDir" value="/opt/CCDA_Validator/configuration/vocabulary/code_repository/" override="true"/>
        <Parameter name="vocabulary.localValueSetRepositoryDir" value="/opt/CCDA_Validator/configuration/vocabulary/valueset_repository/" override="true"/>
        <Parameter name="referenceccda.configFile" value="/opt/CCDA_Validator/configuration/ccdaReferenceValidatorConfig.xml" override="true"/>
    <Parameter name="referenceccda.isDynamicVocab" value="false" override="true"/>
    <Parameter name="referenceccda.configFolder" value="/opt/CCDA_Validator/configuration/" override="true"/>
        <Parameter name="content.scenariosDir" value="/opt/CCDA_Validator/configuration/scenarios/" override="true"/>
</Context>

I actually checked each and every one of these entries, to ensure that they were correct.

But, there may be another issue... Not certain though...

This particular server does not resolve in DNS.

I updated the /etc/hosts file, and made certain that the /etc/nsswitch.conf file was pointing to "files", but it still does not resolve.

I wonder if this could be the issue.

I appreciate that you looked at this thread.

Have a great evening.

**Comment by jxfish2** [comment]
Fixed the DNS lookup issue, but that still did not fix the validator issues.

Still troubleshooting.

I would be more than happy to engage in a screen sharing session with you, if you thought that might help.

**Comment by drbgfc** [comment]
Maybe we can do a screenshare but probably don't have time till tuesday with the release coming up (Monday).

Did u try both of these wars?
https://github.com/siteadmin/reference-ccda-validator/releases/tag/1.0.39
and
https://github.com/siteadmin/reference-ccda-validator/releases/tag/1.0.38

I've never seen so many errors in the log - but, they seem to be related to the content-validator dependency for the most part.

Is it still saying this: "LOADING SCENARIO FILES AT /opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/scenarios/"?
That is really strange. Sounds like your config is not overriding somehow.
Just for the heck of it, try taking all the slashes off the end of the filepaths in your referenceccdaservice.xml values. I don't think it should matter but we don't have them in prod.
Are you sure that your referenceccdaservice.xml is in the exact path of the tomcat server you are running your war with: tomcat installation/conf/Catalina/localhost? I usually create a backup folder inside localhost and copy the config there as sometimes it tomcat deletes it.

**Comment by jxfish2** [comment]
Please note that the scenarios directory is empty.

Is it supposed to be empty?

**Comment by drbgfc** [comment]
It's supposed to contain whatever selection of C-CDA files you want from here: https://github.com/siteadmin/2015-certification-ccda-testdata
Except not in their separated folder heirarchy, just the files in the folder.
However, being empty should not be an issue for startup or using MDHT or vocabulary validation. It would only be an issue if you used the API directly and tried to send a scenario when none existed.

**Comment by jxfish2** [comment]
I think I just fixed the issue.

In one of the more recent documents that I found, it told me to create the following directory:

/opt/tomcat/conf/Catalina/<server name>

Then copy the referenceccdaservice.xml file into this new <server name> directory.

That's exactly what I did.

But, in looking at your notes above, I wondered if I wasn't supposed to put this same war file in the following directory also:

/opt/tomcat/conf/Catalina/localhost

I decided instead of copying the same file into two different directories, where I might need to maintain both files, that I would create a link to both files:

ln referenceccdaservice.xml ../localhost/referenceccdaservice.xml

I then restarted the application, and it came up perfectly, without any errors.

To be honest, I do not know if both of these directories needs to be populated with this war file, but that is how I have it currently, and it is working.

There are no errors in my logs at this time.

Thanks for your help, and have a great weekend.

**Comment by jxfish2** [comment]
Ok, never mind...

The previous errors do not exist any more.

However, I am now getting the following error: 

"nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded"

Any recommendations to fix this?

**Comment by drbgfc** [comment]
That's good news.

<servername> implies localhost
You should only need any of the files in one location only. It doesn't sound like you duplicated the WAR, maybe a type, but instead the referenceccdaservice.xml file? By putting referenceccdaservice.xml in /opt/tomcat/conf/Catalina/localhost is what solved your issue as tomcat knew where to look for the config to override the default settings. Before that it wasn't finding it.
If you can link me to that document you referenced maybe I can make it more clear for others by mentioning localhost as the most likely servername.
My directory looks like this:
-tomcat
--conf
---Catalina
----localhost
----referenceccdaservice.xml
-----backup
-----referenceccdaservice.xml
--webapps
---war

So I know this kind of seems to contradict what I said about not need two of the same file - but it's just a backup - the server does not look at that folder, and it is not needed to boot (the backup).

As for the OOME:
It sounds like a limitation of the current version of the software on your hardware. How much RAM do you have? How much is allocated to tomcat? The software loads all of the vocabulary into RAM (uses an "in-memory database" on boot so it's very RAM intensive. Our prod server has 4GBs of RAM and we use it for this one application exclusively.

**Comment by jxfish2** [comment]
https://github.com/siteadmin/reference-ccda-validator/blob/master/README.md

Server Configuration

1. Place a copy of referenceccdaservice.xml in $CATALINA_BASE/conf/[enginename]/[hostname]/.

"hostname" in linux, means the actual server name.

If you want it to be "localhost", and only "localhost", you should probably say that.

To answer your question about RAM.  This server is currently only running this application.

It has 7GB of RAM, but it is currently only using 2.5GB:

--> free
                 total            used            free                shared   buff/cache   available
Mem:        7123092     2610444     2766552        9348     1746096     4125216
Swap:        2097148                 0     2097148

**Comment by drbgfc** [comment]
I don't think the location is defined by us but rather Tomcat and how you set it up. localhost is likely the default though.

---

For Java7 and below you can include a setenv.sh file in ur tomcat/bin directory
In there you can add something like this (replace with your java home):

#!/bin/bash

JAVA_HOME=/usr/lib/jvm/java-7-oracle

JAVA_OPTS="$JAVA_OPTS -Xmx5120m -XX:MaxPermSize=1024m"



If your using Java8 and above I don't think it does anything though, but won't hurt. The log will tell you it is bypassed.

**Comment by drbgfc** [comment]
Hopefully this helps others:
Update readme to clarify config location
https://github.com/siteadmin/reference-ccda-validator/commit/ff415d0349d1f3d606b142309075df65c4cdc220

**Comment by jxfish2** [comment]
Ok, I finally got the validator to work.

I rolled back the Java 8, and installed Java 7.

Made certain that JAVA_HOME was set correctly.

Created the setenv.sh script.

And, finally, it's up... 

Thanks for all of your help.

**Comment by drbgfc** [comment]
Glad to hear it. Apologies it was such a big effort.

**Comment by drbgfc** [comment]
FYI, based on this issue: I updated the readme with multiple commits: Hopefully that helps others.

Update readme to clarify config location
https://github.com/siteadmin/reference-ccda-validator/commit/ff415d0349d1f3d606b142309075df65c4cdc220

Improve readme: java/tomcat/scenarios/war/config
https://github.com/siteadmin/reference-ccda-validator/commit/b11b7c4f2c1c378c48638395a1a3d22b7ddf4924

Update readme with example directory structure
https://github.com/siteadmin/reference-ccda-validator/commit/c2899df37e1e7b35033d99bf58d0baa28ebc5667

Update readme formatting and tomcat version
https://github.com/siteadmin/reference-ccda-validator/commit/65a31bef991d28c02fb27eb6728448200575a30d

Add "Troubleshooting" section to the readme
https://github.com/siteadmin/reference-ccda-validator/commit/c851c376865b2d7731acef47f41eef85bcf951df

Hopefully overtime the community can help build up the troubleshooting section for complete coverage.

Closing the issue.

Thanks,
Dan

**Comment by jxfish2** [comment]
The main issue was a simple misunderstanding.

Not a big deal.

Have a great weekend.
