### ISSUE TITLE
Swagger page opening, but not populating.

### ISSUE THREAD

**Issue by DSSUSER** [siteadmin/reference-ccda-validator#59]
I have a running instance on a dedicated server, that is running perfectly.

I am trying to port the CCDA Validator to Docker.

I have the entire project inside of a Docker container now, and there are no errors in any of the logfiles.

But, when I attempt to access the Swagger UI, the UI appears, displaying the green Swagger header, but it is not populating the page.

Any ideas why that might be happening?

**Comment by drbgfc** [comment]
This can be closed now as per issue as per issue https://github.com/siteadmin/reference-ccda-validator/issues/64 right? I will close and if not, apologies, I will reopen upon your request.
